// app/(app)/admin/clubs/[clubId]/membership-import/MembershipImportClient.tsx
"use client";
import{useMemo,useState}from"react";import{createReviewRows,reviewIssue,type ReviewRow}from"@/lib/imports/review";
const fields=[["firstName","First name *"],["lastName","Last name *"],["dob","Date of birth"],["email","Member email"],["responsibleAdultEmail","Responsible adult email"],["relationship","Relationship"],["householdKey","Existing family/account reference"]] as const;
export default function MembershipImportClient({clubId}:{clubId:string}){const[file,setFile]=useState<File|null>(null),[inspect,setInspect]=useState<any>(null),[mapping,setMapping]=useState<Record<string,string>>({}),[data,setData]=useState<any>(null),[rows,setRows]=useState<ReviewRow[]>([]),[members,setMembers]=useState<any[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(false);
 async function choose(f:File){setFile(f);setData(null);setRows([]);setLoading(true);setError("");const fd=new FormData();fd.set("file",f);fd.set("inspect","true");const r=await fetch(`/api/admin/clubs/${clubId}/membership-import/preview`,{method:"POST",body:fd});const j=await r.json();setLoading(false);if(!r.ok){setError(j.error);setInspect(null)}else{setInspect(j);setMapping(j.suggested??{})}}
 async function preview(){if(!file)return;setLoading(true);setError("");const fd=new FormData();fd.set("file",file);fd.set("mapping",JSON.stringify(mapping));const[r,mr]=await Promise.all([fetch(`/api/admin/clubs/${clubId}/membership-import/preview`,{method:"POST",body:fd}),fetch(`/api/admin/clubs/${clubId}/membership-import/existing-members`)]);const j=await r.json(),mj=await mr.json();setLoading(false);if(!r.ok){setError(j.error);setData(null);return}setData(j);setRows(createReviewRows(j.rows));if(mr.ok)setMembers(mj.members??[])}
 function patch(i:number,v:Partial<ReviewRow>){setRows(x=>x.map((r,n)=>n===i?{...r,...v}:r))}
 const issues=useMemo(()=>rows.map((r,i)=>({i,msg:reviewIssue(r)})).filter(x=>x.msg),[rows]);const ready=rows.length>0&&issues.length===0;
 const groupOptions=useMemo(()=>Array.from(new Set(rows.map(r=>r.resolvedHouseholdKey).filter(Boolean))),[rows]);
 return <div className="space-y-5"><label className="block rounded-xl border-2 border-dashed bg-white p-6 text-sm"><b>1. Choose membership CSV</b><p className="my-2 text-xs text-slate-600">Nothing is imported and nobody is emailed during preview.</p><input type="file" accept=".csv,text/csv" onChange={e=>e.target.files?.[0]&&choose(e.target.files[0])}/></label>{loading&&<p className="text-sm">Checking file…</p>}{error&&<p className="text-sm text-red-700">{error}</p>}
 {inspect&&<section className="rounded-xl border bg-white p-4 space-y-4"><div><h2 className="font-semibold">2. Match your CSV columns</h2><p className="text-xs text-slate-600">ClubStand has suggested matches. Change anything that is wrong.</p></div><div className="grid gap-3 sm:grid-cols-2">{fields.map(([k,label])=><label key={k} className="text-xs"><span className="mb-1 block font-medium">{label}</span><select className="w-full rounded border p-2" value={mapping[k]??""} onChange={e=>setMapping(m=>({...m,[k]:e.target.value}))}><option value="">Not in this file</option>{inspect.headers.map((h:string)=><option key={h} value={h}>{h}</option>)}</select></label>)}</div><button onClick={preview} className="rounded bg-slate-900 px-4 py-2 text-sm font-medium text-white">Preview {inspect.rowCount} members</button></section>}
 {data&&<><div className="grid gap-3 sm:grid-cols-5"><Stat label="Rows" n={rows.length}/><Stat label="Ready" n={rows.length-issues.length}/><Stat label="Needs attention" n={issues.length}/><Stat label="Possible duplicates" n={data.summary.duplicates}/><Stat label="Proposed accounts" n={data.summary.proposedHouseholds}/></div>
 <div className="rounded-lg bg-blue-50 p-3 text-xs text-blue-900"><b>3. Review ClubStand's suggestions.</b> Correct account groupings and decide what to do with possible duplicates. Shared address is never used to create a household.</div>
 <div className="space-y-3">{rows.map((x,i)=>{const issue=reviewIssue(x);return <article key={x.rowNumber} className={`rounded-xl border bg-white p-4 ${issue?"border-amber-400":""}`}><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><b className="text-sm">Row {x.rowNumber}: {x.editedFirstName} {x.editedLastName}</b><select className="rounded border p-2 text-xs" value={x.decision} onChange={e=>patch(i,{decision:e.target.value as any})}><option value="import_new">Import as new member</option>{x.duplicateMemberId&&<option value="link_existing">Link to existing member</option>}<option value="skip">Do not import this row</option></select></div>
 {x.decision!=="skip"&&<><div className="grid gap-2 sm:grid-cols-3"><Edit label="First name" value={x.editedFirstName} onChange={v=>patch(i,{editedFirstName:v})}/><Edit label="Last name" value={x.editedLastName} onChange={v=>patch(i,{editedLastName:v})}/><Edit label="DOB" value={x.editedDob} onChange={v=>patch(i,{editedDob:v})}/><Edit label="Member email" value={x.editedEmail} onChange={v=>patch(i,{editedEmail:v})}/><Edit label="Responsible adult email" value={x.editedResponsibleAdultEmail} onChange={v=>patch(i,{editedResponsibleAdultEmail:v})}/></div>
 {x.decision==="link_existing"?<label className="mt-3 block text-xs"><b>Existing member</b><select className="mt-1 w-full rounded border p-2" value={x.duplicateMemberId??""} onChange={e=>patch(i,{duplicateMemberId:e.target.value})}>{members.map(m=><option key={m.id} value={m.id}>{m.first_name} {m.last_name}{m.date_of_birth?` · ${m.date_of_birth}`:""}</option>)}</select></label>:<label className="mt-3 block text-xs"><b>Account / household grouping</b><input list={`groups-${i}`} className="mt-1 w-full rounded border p-2" value={x.resolvedHouseholdKey} onChange={e=>patch(i,{resolvedHouseholdKey:e.target.value})} placeholder="e.g. adult:parent@email.com or a new family reference"/><datalist id={`groups-${i}`}>{groupOptions.map(g=><option key={g} value={g}/>)}</datalist><span className="mt-1 block text-slate-500">You can choose an existing suggestion or type a new grouping.</span></label>}</>}
 {issue&&<p className="mt-3 text-xs font-medium text-amber-800">{issue}</p>}{!issue&&x.status==="duplicate"&&x.decision==="link_existing"&&<p className="mt-3 text-xs text-green-700">Possible duplicate resolved by linking to the existing member.</p>}</article>})}</div>
 <section className="rounded-xl border bg-white p-4"><h2 className="font-semibold">4. Import readiness</h2>{ready?<p className="mt-1 text-sm text-green-700">All blocking issues are resolved. This file is ready for the eventual import step.</p>:<p className="mt-1 text-sm text-amber-800">{issues.length} blocking {issues.length===1?"issue":"issues"} still need attention.</p>}<button disabled className="mt-3 rounded bg-slate-300 px-4 py-2 text-sm font-medium text-slate-600">Import {rows.filter(r=>r.decision!=="skip").length} members</button><p className="mt-2 text-xs text-slate-500">Disabled in this checkpoint. v19 reviews and resolves the data only; it cannot create members or send activation emails.</p></section></>}</div>}
function Stat({label,n}:{label:string,n:number}){return <div className="rounded border bg-white p-3"><small>{label}</small><div className="text-xl font-semibold">{n}</div></div>}
function Edit({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="text-xs"><span className="mb-1 block font-medium">{label}</span><input className="w-full rounded border p-2" value={value} onChange={e=>onChange(e.target.value)}/></label>}
