// app/(app)/household/[householdId]/renew/RenewalClient.tsx
"use client";import{useEffect,useState}from"react";import{useRouter}from"next/navigation";
export default function RenewalClient({householdId}:{householdId:string}){const[d,setD]=useState<any>(null),[choices,setChoices]=useState<Record<string,{planId:string;billing:string}>>({}),[busy,setBusy]=useState(""),[err,setErr]=useState("");const router=useRouter();
 async function load(){const r=await fetch(`/api/households/${householdId}/renewal`,{cache:"no-store"}),j=await r.json();if(!r.ok){setErr(j.error);return}setD(j);const c:any={};for(const x of j.members){const p=x.eligiblePlans.find((p:any)=>p.id===x.suggestedPlanId)||x.eligiblePlans[0];if(p)c[x.member.id]={planId:p.id,billing:p.allowAnnual?"annual":"monthly"}}setChoices(c)}
 useEffect(()=>{load()},[]);
 async function renew(memberId:string){const c=choices[memberId];if(!c)return;setBusy(memberId);setErr("");const r=await fetch(`/api/households/${householdId}/renewal/create`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({memberId,planId:c.planId,billingPeriod:c.billing})}),j=await r.json();setBusy("");if(!r.ok){setErr(j.error+(j.details?` ${j.details}`:""));return}await load();router.refresh()}
 async function pay(){setBusy("payment");setErr("");const r=await fetch("/api/payments/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({householdId,membershipYear:d.renewalYear,renewalCheckout:true})}),j=await r.json();setBusy("");if(!r.ok){setErr(j.error||"Renewal is not ready for payment.");return}if(j.url)window.location.href=j.url}
 if(err&&!d)return <p className="text-sm text-red-700">{err}</p>;if(!d)return <p className="text-sm">Loading renewal…</p>;
 return <div className="space-y-5">{err&&<div className="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">{err}</div>}<div className="rounded-xl border bg-blue-50 p-4 text-sm"><b>Renewing for membership year {d.renewalYear}</b><p className="mt-1 text-xs">Nobody needs to register again. Check each person and confirm the membership they should have next year. Existing {d.currentYear} membership remains in history.</p></div>
 <section className="rounded-xl border bg-white p-4"><h2 className="font-semibold">Renewal progress</h2><div className="mt-3 grid gap-2 sm:grid-cols-4"><Box label="Memberships prepared" value={`${d.progress.prepared}/${d.progress.totalMembers}`}/><Box label="Forms outstanding" value={String(d.progress.formsMissing)}/><Box label="Approvals pending" value={String(d.progress.approvalPending)}/><Box label="Payment" value={d.progress.readyForPayment?"Ready":"Not ready"}/></div>{d.householdMissingForms?.length>0&&<div className="mt-3 rounded bg-amber-50 p-3 text-xs text-amber-900"><b>Household forms to review:</b> {d.householdMissingForms.join(", ")} <a className="ml-2 underline" href={`/household/${householdId}/renew/household-forms`}>Complete household forms</a></div>}</section>
 {d.members.map((x:any)=>{const c=choices[x.member.id],p=x.eligiblePlans.find((z:any)=>z.id===c?.planId);return <section key={x.member.id} className="rounded-xl border bg-white p-4"><div className="flex flex-wrap justify-between gap-2"><div><h2 className="font-semibold">{x.member.first_name} {x.member.last_name}</h2><p className="text-xs text-slate-500">Current/most recent: {x.previous?.plan?.name??"No membership recorded"}{x.previous?` · ${x.previous.membership_year}`:""}</p></div>{x.alreadyRenewed&&<span className="rounded-full bg-green-50 px-3 py-1 text-xs text-green-700">Renewal prepared</span>}</div>
 {x.alreadyRenewed&&x.missingForms?.length>0&&<div className="mt-3 rounded bg-amber-50 p-3 text-xs text-amber-900"><b>Forms to review:</b> {x.missingForms.join(", ")} <a className="ml-2 underline" href={`/household/${householdId}/safeguarding?member=${x.member.id}&returnTo=renew`}>Complete forms</a></div>}
 {x.alreadyRenewed&&x.renewalSubscription?.review_status==="pending"&&<p className="mt-3 text-xs text-amber-800">Waiting for club approval.</p>}
 {!x.alreadyRenewed&&(x.eligiblePlans.length?<div className="mt-4 grid gap-3 sm:grid-cols-3"><label className="text-xs sm:col-span-2">Membership<select className="mt-1 w-full rounded border p-2" value={c?.planId??""} onChange={e=>{const np=x.eligiblePlans.find((z:any)=>z.id===e.target.value);setChoices(v=>({...v,[x.member.id]:{planId:e.target.value,billing:np?.allowAnnual?"annual":"monthly"}}))}}>{x.eligiblePlans.map((z:any)=><option key={z.id} value={z.id}>{z.name}{z.id===x.suggestedPlanId?" · same as this year":""}</option>)}</select></label><label className="text-xs">Payment frequency<select className="mt-1 w-full rounded border p-2" value={c?.billing??"annual"} onChange={e=>setChoices(v=>({...v,[x.member.id]:{...v[x.member.id],billing:e.target.value}}))}>{p?.allowAnnual&&<option value="annual">Annual</option>}{p?.allowMonthly&&<option value="monthly">Monthly</option>}</select></label><div className="sm:col-span-3 flex justify-end"><button disabled={busy===x.member.id} onClick={()=>renew(x.member.id)} className="rounded bg-slate-900 px-4 py-2 text-xs font-medium text-white">{busy===x.member.id?"Saving…":"Prepare renewal"}</button></div></div>:<p className="mt-3 text-sm text-amber-800">No currently available membership plan matches this person for {d.renewalYear}. The club will need to review their options.</p>)}</section>})}
 <section className="rounded-xl border bg-white p-4"><h2 className="font-semibold">Complete renewal</h2>{d.progress.readyForPayment?<><p className="mt-1 text-sm text-green-700">Membership choices, required forms and approvals are complete. The household renewal is ready for payment.</p><button onClick={pay} disabled={busy==="payment"} className="mt-3 rounded bg-slate-900 px-4 py-2 text-sm font-medium text-white">{busy==="payment"?"Opening payment…":"Continue to payment"}</button></>:<p className="mt-1 text-sm text-slate-600">Complete the items above before payment becomes available. Preparing a renewal never overwrites the previous year's membership.</p>}</section></div>}
function Box({label,value}:{label:string;value:string}){return <div className="rounded border bg-slate-50 p-3"><div className="text-xs text-slate-500">{label}</div><div className="font-semibold">{value}</div></div>}
