// app/api/memberships/complete-registration/route.ts
import { createHash } from 'node:crypto';
import { NextResponse } from 'next/server';
import { supabaseServerClient } from '@/lib/supabaseServer';
import { DEFAULT_MEMBERSHIP_SETTINGS, currentMembershipYear } from '@/lib/membership/rules';
import { evaluatePlanEligibility } from '@/lib/membership/eligibility';
import { calculateJoiningPrice } from '@/lib/membership/joiningPrice';
type Person={firstName:string;lastName:string;dob?:string;role:'player'|'supporter';planId:string;billing:'annual'|'monthly';responses?:Record<string,boolean|string>};
type Payload={invitationId:string;token:string;household:{firstName:string;lastName:string;email:string;phone?:string;addressLine1?:string;addressLine2?:string;townCity?:string;postcode?:string};people:Person[];householdResponses?:Record<string,boolean|string>};
export async function POST(req:Request){
 const body=(await req.json().catch(()=>null)) as Payload|null;if(!body?.invitationId||!body.token||!body.people?.length)return NextResponse.json({error:'Registration details are incomplete.'},{status:400});
 const authHeader=req.headers.get('authorization')||'';const accessToken=authHeader.startsWith('Bearer ')?authHeader.slice(7):'';if(!accessToken)return NextResponse.json({error:'Sign in to complete registration.'},{status:401});
 const {data:authData,error:authError}=await supabaseServerClient.auth.getUser(accessToken);const authEmail=authData.user?.email?.trim().toLowerCase();if(authError||!authData.user||!authEmail)return NextResponse.json({error:'Your sign-in session could not be verified.'},{status:401});
 const hash=createHash('sha256').update(body.token).digest('hex');const {data:inv}=await supabaseServerClient.from('membership_invitations').select('id,club_id,email,status,expires_at').eq('id',body.invitationId).eq('token_hash',hash).maybeSingle();
 if(!inv)return NextResponse.json({error:'This invitation is not valid.'},{status:404});if(['revoked','expired','completed'].includes(inv.status)||new Date(inv.expires_at).getTime()<=Date.now())return NextResponse.json({error:'This invitation is no longer available.'},{status:410});
 const email=String(body.household.email||'').trim().toLowerCase();if(email!==String(inv.email).trim().toLowerCase())return NextResponse.json({error:'The registration email does not match the invitation.'},{status:400});if(authEmail!==email)return NextResponse.json({error:'You must be signed in with the email address that was invited.'},{status:403});
 if(body.people.some(p=>!p.firstName.trim()||!p.lastName.trim()||!p.planId||(p.role==='player'&&!p.dob)))return NextResponse.json({error:'Complete the details and membership for every person joining.'},{status:400});
 const planIds=[...new Set(body.people.map(p=>p.planId))];const [{data:plans,error:pe},{data:questions,error:qe},{data:settingsRow}]=await Promise.all([
  supabaseServerClient.from('membership_plans').select('id,price_pennies,annual_price_pennies,monthly_price_pennies,is_player_plan,is_junior_only,minimum_age,maximum_age,requires_approval,mid_season_treatment,trial_days,is_visible_online,allow_annual,allow_monthly').eq('club_id',inv.club_id).in('id',planIds),
  supabaseServerClient.from('club_consent_questions').select('id,required,applies_to').eq('club_id',inv.club_id).eq('is_active',true),
  supabaseServerClient.from('club_membership_settings').select('*').eq('club_id',inv.club_id).maybeSingle()
 ]);if(pe||qe||!plans||plans.length!==planIds.length)return NextResponse.json({error:'Membership configuration could not be validated.'},{status:400});const pm=new Map(plans.map(p=>[p.id,p]));
 const settings={...DEFAULT_MEMBERSHIP_SETTINGS,...(settingsRow??{})};const membershipYear=currentMembershipYear(new Date(),settings);
 const hasAnswer=(v:unknown)=>v===true||(typeof v==='string'&&v.trim().length>0);
 for(const person of body.people){const plan=pm.get(person.planId)!;const eligibility=evaluatePlanEligibility({dob:person.dob,role:person.role,membershipYear,settings,plan});if(!eligibility.eligible)return NextResponse.json({error:`${person.firstName} is not eligible for this membership. ${eligibility.reason??''}`.trim()},{status:400});if(plan.is_visible_online===false)return NextResponse.json({error:`The selected membership is not available online for ${person.firstName}.`},{status:400});if(person.billing==='monthly'&&(!settings.allow_monthly||!plan.allow_monthly||plan.monthly_price_pennies==null))return NextResponse.json({error:`Monthly payment is not available for ${person.firstName}'s membership.`},{status:400});if(person.billing==='annual'&&(!settings.allow_annual||!plan.allow_annual||plan.annual_price_pennies==null) && plan.price_pennies==null)return NextResponse.json({error:`Annual payment is not available for ${person.firstName}'s membership.`},{status:400});
  for(const q of questions??[]){if(!q.required)continue;const scope=q.applies_to??'all';const relevant=scope==='all'||(scope==='junior'&&eligibility.junior===true)||(scope==='adult'&&eligibility.junior===false);if(relevant&&!hasAnswer(person.responses?.[q.id]))return NextResponse.json({error:`Complete all required forms and consents for ${person.firstName}.`},{status:400});}
 }
 for(const q of questions??[]){if(q.required&&(q.applies_to==='household'||q.applies_to==='parent')&&!hasAnswer(body.householdResponses?.[q.id]))return NextResponse.json({error:'Complete all required household declarations.'},{status:400});}
 const {data:existing}=await supabaseServerClient.from('households').select('id').eq('club_id',inv.club_id).or(`primary_email.ilike.${email},secondary_email.ilike.${email}`).limit(1).maybeSingle();if(existing)return NextResponse.json({error:'This email is already connected to a household.',householdId:existing.id},{status:409});
 let householdId:string|undefined;const memberIds:string[]=[];const subIds:string[]=[];const responseIds:string[]=[];
 try{const h=await supabaseServerClient.from('households').insert({club_id:inv.club_id,primary_email:email,name:`${body.household.firstName} ${body.household.lastName}`.trim(),phone:body.household.phone?.trim()||null,address_line1:body.household.addressLine1?.trim()||null,address_line2:body.household.addressLine2?.trim()||null,town_city:body.household.townCity?.trim()||null,postcode:body.household.postcode?.trim()||null}).select('id').single();if(h.error||!h.data)throw new Error(h.error?.message||'Could not create household');householdId=h.data.id;
  const householdRows=Object.entries(body.householdResponses??{}).map(([question_id,value])=>({club_id:inv.club_id,question_id,household_id:householdId,member_id:null,response:{value},completed_at:new Date().toISOString()}));if(householdRows.length){const rr=await supabaseServerClient.from('member_consent_responses').insert(householdRows).select('id');if(rr.error)throw new Error(rr.error.message);responseIds.push(...(rr.data??[]).map(x=>x.id));}
  for(const person of body.people){const m=await supabaseServerClient.from('members').insert({club_id:inv.club_id,household_id:householdId,first_name:person.firstName.trim(),last_name:person.lastName.trim(),date_of_birth:person.dob||null,member_type:person.role}).select('id').single();if(m.error||!m.data)throw new Error(m.error?.message||`Could not add ${person.firstName}`);memberIds.push(m.data.id);const plan=pm.get(person.planId)!;const fullAmount=person.billing==='monthly'?(plan.monthly_price_pennies??0):(plan.annual_price_pennies??plan.price_pennies??0);const quote=calculateJoiningPrice({fullAmountPennies:fullAmount,billing:person.billing,now:new Date(),membershipYear,settings,planTreatment:plan.mid_season_treatment,planTrialDays:plan.trial_days});const trialEndsAt=quote.treatment==='trial'&&quote.trialDays>0?new Date(Date.now()+quote.trialDays*86400000).toISOString():null;const s=await supabaseServerClient.from('membership_subscriptions').insert({club_id:inv.club_id,household_id:householdId,member_id:m.data.id,plan_id:person.planId,amount_pennies:quote.amountPennies,status:'pending',joining_treatment:quote.treatment,trial_ends_at:trialEndsAt,requires_manual_review:quote.requiresManualReview||plan.requires_approval===true,review_status:(quote.requiresManualReview||plan.requires_approval===true)?'pending':'not_required'}).select('id').single();if(s.error||!s.data)throw new Error(s.error?.message||`Could not create ${person.firstName}'s membership`);subIds.push(s.data.id);
   const rows=Object.entries(person.responses??{}).map(([question_id,value])=>({club_id:inv.club_id,question_id,household_id:householdId,member_id:m.data.id,response:{value},completed_at:new Date().toISOString()}));if(rows.length){const rr=await supabaseServerClient.from('member_consent_responses').insert(rows).select('id');if(rr.error)throw new Error(rr.error.message);responseIds.push(...(rr.data??[]).map(x=>x.id));}}
  const now=new Date().toISOString();const done=await supabaseServerClient.from('membership_invitations').update({status:'completed',completed_at:now,started_at:now}).eq('id',inv.id);if(done.error)throw new Error(done.error.message);return NextResponse.json({success:true,householdId,memberCount:memberIds.length,subscriptionCount:subIds.length});
 }catch(err:any){if(responseIds.length)await supabaseServerClient.from('member_consent_responses').delete().in('id',responseIds);if(subIds.length)await supabaseServerClient.from('membership_subscriptions').delete().in('id',subIds);if(memberIds.length)await supabaseServerClient.from('members').delete().in('id',memberIds);if(householdId)await supabaseServerClient.from('households').delete().eq('id',householdId);console.error('Complete registration failed',err);return NextResponse.json({error:'Registration could not be completed. Nothing has been saved.',details:err?.message},{status:500});}
}
