// app/api/households/[householdId]/renewal/route.ts
import{NextResponse}from"next/server";import{requireHouseholdAccess}from"@/lib/auth/householdAccess";import{DEFAULT_MEMBERSHIP_SETTINGS,currentMembershipYear,isJunior}from"@/lib/membership/rules";import{evaluatePlanEligibility}from"@/lib/membership/eligibility";import{consentAppliesTo}from"@/lib/consent/applicability";
export async function GET(_req:Request,{params}:{params:Promise<{householdId:string}>}){const{householdId}=await params;const a=await requireHouseholdAccess(householdId);if(!a.ok)return NextResponse.json({error:a.error},{status:a.status});const s=a.supabase,{data:h}=await s.from("households").select("id,club_id").eq("id",householdId).maybeSingle();if(!h)return NextResponse.json({error:"Household not found"},{status:404});const{data:sr}=await s.from("club_membership_settings").select("*").eq("club_id",h.club_id).maybeSingle();const settings={...DEFAULT_MEMBERSHIP_SETTINGS,...(sr??{})},currentYear=currentMembershipYear(new Date(),settings),renewalYear=currentYear+1;
 const[{data:members},{data:subs},{data:plans},{data:questions},{data:versions},{data:acceptances}]=await Promise.all([
 s.from("members").select("id,first_name,last_name,date_of_birth,member_type").eq("household_id",householdId).eq("club_id",h.club_id),
 s.from("membership_subscriptions").select("id,member_id,plan_id,status,membership_year,requires_manual_review,review_status,amount_pennies,plan:membership_plans(id,name)").eq("household_id",householdId).order("membership_year",{ascending:false}),
 s.from("membership_plans").select("id,name,is_junior_only,is_player_plan,minimum_age,maximum_age,requires_approval,allow_annual,allow_monthly,annual_price_pennies,monthly_price_pennies,price_pennies").eq("club_id",h.club_id).eq("is_active",true),
 s.from("club_consent_questions").select("id,label,required,applies_to").eq("club_id",h.club_id).eq("is_active",true),
 s.from("club_policy_versions").select("id,question_id,version").eq("club_id",h.club_id).is("retired_at",null).order("version",{ascending:false}),
 s.from("member_policy_acceptances").select("member_id,policy_version_id").eq("household_id",householdId).is("revoked_at",null)
 ]);
 const latest=new Map<string,any>();for(const v of versions??[])if(!latest.has(v.question_id))latest.set(v.question_id,v);const accepted=new Set((acceptances??[]).map((x:any)=>`${x.member_id??"household"}:${x.policy_version_id}`));
 const householdMissing=(questions??[]).filter((q:any)=>q.required&&q.applies_to==="household").filter((q:any)=>{const v=latest.get(q.id);return v&&!accepted.has(`household:${v.id}`)}).map((q:any)=>q.label);
 const rows=(members??[]).map((m:any)=>{const history=(subs??[]).filter((x:any)=>x.member_id===m.id),previous=history.find((x:any)=>x.membership_year===currentYear)||history[0]||null,renewal=history.find((x:any)=>x.membership_year===renewalYear&&["pending","active","paused"].includes(x.status))||null;const eligible=(plans??[]).filter((p:any)=>evaluatePlanEligibility({dob:m.date_of_birth,role:m.member_type==="supporter"?"supporter":"player",membershipYear:renewalYear,settings,plan:p}).eligible).map((p:any)=>({id:p.id,name:p.name,allowAnnual:!!p.allow_annual,allowMonthly:!!p.allow_monthly,annualPricePennies:p.annual_price_pennies??p.price_pennies,monthlyPricePennies:p.monthly_price_pennies??p.price_pennies,requiresApproval:!!p.requires_approval}));const context=m.member_type==="supporter"?"parent":m.date_of_birth&&isJunior(m.date_of_birth,renewalYear,settings)===true?"junior":"adult";const missingForms=(questions??[]).filter((q:any)=>q.required&&q.applies_to!=="household"&&consentAppliesTo(q.applies_to,context as any)).filter((q:any)=>{const v=latest.get(q.id);return v&&!accepted.has(`${m.id}:${v.id}`)}).map((q:any)=>q.label);return{member:m,previous,alreadyRenewed:!!renewal,renewalSubscription:renewal,eligiblePlans:eligible,suggestedPlanId:eligible.some((p:any)=>p.id===previous?.plan_id)?previous?.plan_id:null,missingForms,formsComplete:missingForms.length===0}});
 const prepared=rows.filter((x:any)=>x.alreadyRenewed),approvalPending=prepared.filter((x:any)=>x.renewalSubscription?.requires_manual_review||x.renewalSubscription?.review_status==="pending").length,formsMissing=prepared.reduce((n:number,x:any)=>n+x.missingForms.length,0)+householdMissing.length,allPrepared=rows.length>0&&rows.every((x:any)=>x.alreadyRenewed),readyForPayment=allPrepared&&approvalPending===0&&formsMissing===0;
 return NextResponse.json({currentYear,renewalYear,members:rows,householdMissingForms:householdMissing,progress:{totalMembers:rows.length,prepared:prepared.length,approvalPending,formsMissing,allPrepared,readyForPayment},note:"Historic acceptances remain unchanged. Only the latest published version of a required form counts for this renewal."})}
