// lib/imports/membershipCsv.ts
export const IMPORT_FIELDS = ["firstName","lastName","dob","email","responsibleAdultEmail","relationship","householdKey"] as const;
export type ImportField = typeof IMPORT_FIELDS[number];
export type ColumnMapping = Partial<Record<ImportField,string>>;
export type ImportPreviewRow={rowNumber:number;firstName:string;lastName:string;dob:string;email:string;responsibleAdultEmail:string;relationship:string;householdKey:string;proposedHouseholdKey:string;status:"ready"|"pending"|"missing_responsible_adult"|"invalid"|"duplicate";message:string;duplicateMemberId?:string};
const aliases:Record<ImportField,string[]>={
 firstName:["first name","firstname","forename","member first name"],lastName:["last name","lastname","surname","member last name"],dob:["date of birth","dob","birth date"],email:["email","email address","member email"],responsibleAdultEmail:["parent email","guardian email","responsible adult email","payer email"],relationship:["relationship","relationship to account holder"],householdKey:["household id","family id","family number","account id","payer id","household key"]
};
export const normaliseHeader=(s:string)=>s.trim().toLowerCase().replace(/[_-]+/g," ").replace(/\s+/g," ");
function split(line:string){const out:string[]=[];let x="",q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){x+='"';i++}else q=!q}else if(c===","&&!q){out.push(x.trim());x=""}else x+=c}out.push(x.trim());return out}
function age(dob:string){const d=new Date(dob),n=new Date();if(Number.isNaN(d.getTime()))return null;let a=n.getFullYear()-d.getFullYear();if(n.getMonth()<d.getMonth()||(n.getMonth()===d.getMonth()&&n.getDate()<d.getDate()))a--;return a}
export function inspectMembershipCsv(text:string){const lines=text.replace(/^\uFEFF/,"").split(/\r?\n/).filter(x=>x.trim());if(lines.length<2)throw new Error("The CSV needs a header row and at least one member.");const headers=split(lines[0]);const suggested:ColumnMapping={};for(const field of IMPORT_FIELDS){const i=headers.findIndex(h=>aliases[field].includes(normaliseHeader(h)));if(i>=0)suggested[field]=headers[i]}return{headers,suggested,rowCount:lines.length-1}}
export function previewMembershipCsv(text:string,mapping?:ColumnMapping){
 const lines=text.replace(/^\uFEFF/,"").split(/\r?\n/).filter(x=>x.trim());if(lines.length<2)throw new Error("The CSV needs a header row and at least one member.");const headers=split(lines[0]);const inspection=inspectMembershipCsv(text);const use={...inspection.suggested,...mapping};
 const index:Partial<Record<ImportField,number>>={};for(const field of IMPORT_FIELDS){const chosen=use[field];if(chosen){const i=headers.indexOf(chosen);if(i>=0)index[field]=i}}
 if(index.firstName==null||index.lastName==null)throw new Error("Map the first name and last name columns before previewing members.");const val=(cells:string[],k:ImportField)=>index[k]==null?"":(cells[index[k]!]??"").trim();
 const rows:ImportPreviewRow[]=lines.slice(1).map((line,i)=>{const c=split(line),firstName=val(c,"firstName"),lastName=val(c,"lastName"),dob=val(c,"dob"),email=val(c,"email"),responsibleAdultEmail=val(c,"responsibleAdultEmail"),relationship=val(c,"relationship"),householdKey=val(c,"householdKey");let status:ImportPreviewRow["status"]="ready",message="Ready to review";const a=dob?age(dob):null;if(!firstName||!lastName){status="invalid";message="Name is incomplete"}else if(dob&&a==null){status="invalid";message="Date of birth could not be read"}else if(a!=null&&a<18&&!responsibleAdultEmail&&!householdKey){status="missing_responsible_adult";message="Under 18: responsible adult or family/account reference needed"}else if(!email&&!responsibleAdultEmail&&!householdKey){status="pending";message="No account/family link or contact email found"}const proposedHouseholdKey=householdKey?`source:${householdKey}`:responsibleAdultEmail?`adult:${responsibleAdultEmail.toLowerCase()}`:(a!=null&&a>=18&&email?`adult:${email.toLowerCase()}`:"");return{rowNumber:i+2,firstName,lastName,dob,email,responsibleAdultEmail,relationship,householdKey,proposedHouseholdKey,status,message}});
 return{headers,mapping:use,rows,summary:{total:rows.length,ready:rows.filter(r=>r.status==="ready").length,needsAttention:rows.filter(r=>r.status!=="ready").length,under18MissingAdult:rows.filter(r=>r.status==="missing_responsible_adult").length,duplicates:0,proposedHouseholds:new Set(rows.map(r=>r.proposedHouseholdKey).filter(Boolean)).size}};
}
