// app/(app)/admin/clubs/[clubId]/pricing/rules/PricingRulesClient.tsx
"use client";
import {useEffect,useState} from "react";
type Plan={id:string;name:string};
type Rule={id:string;name:string|null;rule_type:"household_cap"|"multi_member_discount"|"nth_member_discount"|"bundle";applies_to_plan_ids:string[]|null;min_quantity:number|null;cap_amount_pennies:number|null;discount_amount_pennies:number|null;discount_percent:number|null;bundle_price_pennies:number|null;bundle_adults_required:number|null;bundle_juniors_required:number|null;bundle_juniors_any:boolean|null;discount_from_position:number|null;maximum_discounted_members:number|null;required_plan_ids:string[]|null;priority:number;is_active:boolean};
const blank=(type:Rule["rule_type"]="nth_member_discount"):Rule=>({id:"",name:null,rule_type:type,applies_to_plan_ids:null,min_quantity:2,cap_amount_pennies:null,discount_amount_pennies:null,discount_percent:null,bundle_price_pennies:null,bundle_adults_required:0,bundle_juniors_required:0,bundle_juniors_any:false,discount_from_position:2,maximum_discounted_members:null,required_plan_ids:null,priority:100,is_active:true});
const pounds=(p:number|null)=>p==null?"":String(p/100), pennies=(v:string)=>v===""?null:Math.round(Number(v)*100);
export default function PricingRulesClient({clubId}:{clubId:string}){
 const[plans,setPlans]=useState<Plan[]>([]),[rules,setRules]=useState<Rule[]>([]),[msg,setMsg]=useState(""),[err,setErr]=useState(""),[saving,setSaving]=useState(false);
 useEffect(()=>{Promise.all([fetch(`/api/admin/clubs/${clubId}/membership-plans`).then(r=>r.json()),fetch(`/api/admin/clubs/${clubId}/pricing-rules`).then(r=>r.json())]).then(([p,r])=>{setPlans(p.plans??[]);setRules(r.rules??[])}).catch(e=>setErr(e.message))},[clubId]);
 const patch=(i:number,x:Partial<Rule>)=>setRules(v=>v.map((r,n)=>n===i?{...r,...x}:r));
 const move=(i:number,dir:-1|1)=>setRules(v=>{const n=i+dir;if(n<0||n>=v.length)return v;const copy=[...v];[copy[i],copy[n]]=[copy[n],copy[i]];return copy});
 const checks=(i:number,key:"applies_to_plan_ids"|"required_plan_ids")=><div className="grid gap-1 sm:grid-cols-2">{plans.map(p=><label key={p.id} className="text-xs"><input type="checkbox" className="mr-1" checked={(rules[i][key]??[]).includes(p.id)} onChange={e=>{const s=new Set(rules[i][key]??[]);e.target.checked?s.add(p.id):s.delete(p.id);patch(i,{[key]:[...s]} as any)}}/>{p.name}</label>)}</div>;
 async function save(){setSaving(true);setErr("");setMsg("");try{const res=await fetch(`/api/admin/clubs/${clubId}/pricing-rules`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({rules:rules.map((r,i)=>({...r,priority:(i+1)*10}))})});const j=await res.json();if(!res.ok)throw new Error(j.error||"Could not save");setRules(j.rules??[]);setMsg("Pricing rules saved.")}catch(e:any){setErr(e.message)}finally{setSaving(false)}}
 return <div className="space-y-4">
  <div className="rounded-xl border bg-slate-50 p-4 text-sm"><b>Build the club's family pricing as a set of rules.</b><p className="mt-1 text-xs text-slate-600">Examples: “second junior gets £20 off”, “third child onwards 50% off”, “2 adults + any junior = £300”, or “household never pays more than £400”. Rules are data, not Rainhill-specific code. Order matters: the first matching family bundle wins, so use Up/Down to set priority.</p></div>
  {err&&<div className="rounded border border-red-200 bg-red-50 p-2 text-sm text-red-700">{err}</div>}{msg&&<div className="rounded border border-emerald-200 bg-emerald-50 p-2 text-sm">{msg}</div>}
  {rules.map((r,i)=><div key={r.id||`new-${i}`} className="rounded-xl border bg-white p-4 shadow-sm space-y-3">
   <div className="flex flex-wrap items-center gap-2"><input className="min-w-56 flex-1 rounded border px-2 py-1 font-medium" placeholder="Rule name, e.g. Second junior discount" value={r.name??""} onChange={e=>patch(i,{name:e.target.value})}/><select className="rounded border px-2 py-1 text-sm" value={r.rule_type} onChange={e=>patch(i,{rule_type:e.target.value as any})}><option value="nth_member_discount">Nth member discount</option><option value="multi_member_discount">Multi-member discount</option><option value="bundle">Family bundle</option><option value="household_cap">Household cap</option></select><label className="text-xs"><input type="checkbox" checked={r.is_active} onChange={e=>patch(i,{is_active:e.target.checked})}/> Active</label><button disabled={i===0} className="text-xs disabled:opacity-30" onClick={()=>move(i,-1)}>↑ Up</button><button disabled={i===rules.length-1} className="text-xs disabled:opacity-30" onClick={()=>move(i,1)}>↓ Down</button><button className="text-xs text-red-700" onClick={()=>setRules(v=>v.filter((_,n)=>n!==i))}>Remove</button></div>
   {(r.rule_type==="nth_member_discount"||r.rule_type==="multi_member_discount")&&<div className="grid gap-4 md:grid-cols-3"><label className="text-sm">Discount from member number<input type="number" min="2" className="mt-1 w-full rounded border px-2 py-1" value={r.discount_from_position??r.min_quantity??2} onChange={e=>patch(i,{discount_from_position:Number(e.target.value),min_quantity:Number(e.target.value)})}/></label><label className="text-sm">Fixed discount (£)<input type="number" min="0" step=".01" className="mt-1 w-full rounded border px-2 py-1" value={pounds(r.discount_amount_pennies)} onChange={e=>patch(i,{discount_amount_pennies:pennies(e.target.value),discount_percent:null})}/></label><label className="text-sm">Or percentage (%)<input type="number" min="0" max="100" className="mt-1 w-full rounded border px-2 py-1" value={r.discount_percent??""} onChange={e=>patch(i,{discount_percent:e.target.value===""?null:Number(e.target.value),discount_amount_pennies:null})}/></label><label className="text-sm">Maximum members discounted <span className="text-xs text-slate-500">(blank = everyone from that position)</span><input type="number" min="1" className="mt-1 w-full rounded border px-2 py-1" value={r.maximum_discounted_members??""} onChange={e=>patch(i,{maximum_discounted_members:e.target.value===""?null:Number(e.target.value)})}/></label><div className="md:col-span-3"><div className="text-xs font-medium mb-1">Only count these plans (none selected = all)</div>{checks(i,"applies_to_plan_ids")}</div></div>}
   {r.rule_type==="bundle"&&<div className="grid gap-4 md:grid-cols-2"><label className="text-sm">Family price (£)<input type="number" step=".01" className="mt-1 w-full rounded border px-2 py-1" value={pounds(r.bundle_price_pennies)} onChange={e=>patch(i,{bundle_price_pennies:pennies(e.target.value)})}/></label><div><div className="text-xs font-medium mb-1">Plans that must be present</div>{checks(i,"required_plan_ids")}</div><label className="text-sm">Adults required<input type="number" min="0" className="ml-2 w-20 rounded border px-2 py-1" value={r.bundle_adults_required??0} onChange={e=>patch(i,{bundle_adults_required:Number(e.target.value)})}/></label><label className="text-sm">Juniors required<input type="number" min="0" className="ml-2 w-20 rounded border px-2 py-1" value={r.bundle_juniors_required??0} onChange={e=>patch(i,{bundle_juniors_required:Number(e.target.value)})}/></label></div>}
   {r.rule_type==="household_cap"&&<label className="block text-sm">Maximum household membership fee (£)<input type="number" step=".01" className="ml-2 rounded border px-2 py-1" value={pounds(r.cap_amount_pennies)} onChange={e=>patch(i,{cap_amount_pennies:pennies(e.target.value)})}/></label>}
  </div>)}
  <div className="flex flex-wrap justify-between gap-2"><button className="rounded border bg-white px-3 py-2 text-sm" onClick={()=>setRules(v=>[...v,blank()])}>+ Add pricing rule</button><button disabled={saving} className="rounded bg-slate-900 px-4 py-2 text-sm font-medium text-white disabled:opacity-50" onClick={save}>{saving?"Saving…":"Save pricing rules"}</button></div>
 </div>
}